### ISSUE TITLE
Проблема с загруской

### ISSUE THREAD

**Issue by Roma1825** [Shuudoushi/SecureOS#63]
Пишет обновится до lua 5.2 (мод последней версии а на компьютере ну настоящем lua 5.3)что делать,

**Comment by kcinnaJlol** [comment]
Translation to english:

> Problem loading

> Writes will be updated to lua 5.2 (mod of the latest version and on the computer, the present lua 5.3) what to do,

My correction:

>Problem with loading 

> Writes will be updated to lua 5.2 (mod of the latest version and on the computer, the present lua 5.3), what to do?
